services:
  postgres:
    image: postgres:17-alpine
    restart: no
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    env_file: .env
    ports:
      - 5454:5432
